import time



def chapter_endgame():
    print("")
    print("")
    print("Thank you for playing the game.")
    print("")
    time.sleep(3.5)
    print(f"Did you get the ending you wanted {name}?")
    print("")
    time.sleep(3.5)
    print("If not, play the game again.")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    time.sleep(5)
    start_game()


def chapter_nine():
    print("")
    print("")
    print("Chapter 9")
    print("")
    time.sleep(3.5)
    print("James: Now I’ve just gotten a very nice new gun and I want to use it, so one of you will die - pick who.")
    print("")
    time.sleep(3.5)
    decision = input("Do you save your wife or yourself? [Wife/Yourself]")
    
    if decision == "Wife" or decision == "wife" or decision == "Her" or decision == "her":
        print("")
        print("You know you’re the reason she’s in this situation, you wanted to move to England, you promised her a better life, you should be the one who takes the bullet. You look at her, admiring her beauty one last time and look back at James, he raises his gun and everything turns black.")
        print("")
        time.sleep(6)
        print("THE END.")
        time.sleep(3.5)
        print("")
        print("")
        chapter_endgame()
    
    elif decision == "Yourself" or decision == "yourself" or decision == "Me" or decision == "me":
        print("")
        print("")
        print(f"You aren’t ready to go, you came to this country for a better life, you aren’t stopping now. You turn to look at her and whisper “I’m sorry”, you close your eyes and hear a gunshot and scream. Is it a better life now {name}? THE END.")
        print("")
        print("")
        time.sleep(3.5)
        chapter_endgame()
    
    else:
        print("")
        print("")
        print("Incorrect answer, reloading chapter.")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        time.sleep(3.5)
        chapter_nine()


def chapter_eight():
    print("")
    print("")
    print("Chapter 8")
    print("")
    time.sleep(3.5)
    print("You wake up and you’re chained to a pole in a dark and dingy room.")
    print("")
    time.sleep(5)
    print("You heard footsteps come towards you and a woman is thrown into the room with a man standing behind. You realise it’s your wife and you start to cry.")
    print("")
    time.sleep(3.5)
    print("Your eyes adjust to the light and you realise the man is James and you stare, stunned.")
    print("")
    time.sleep(5)
    decision = input("Do you scream at him for trapping you and your wife or demand to explain what's happening? [Scream/Demand]")
    
    if decision == "Scream" or decision == "scream" or decision == "Wife" or decision == "wife":
        print("")
        print("")
        print(f"James looks at you in disgust, pulling a gun from his jacket 'Oh {name}, you paid your debt, I don’t need you anymore' He points the gun at you 'thanks for your business'. GAME OVER.")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        time.sleep(3.5)
        start_game()
    
    elif decision == "Demand" or decision == "demand" or decision == "Explain" or decision == "explain":
        print("")
        print("")
        print(f"James: Honestly {name}, haven’t you figured it out? I’m the Red Raven, you took my money and now I’m taking it back - thanks by the way, your stealing efforts haven’t gone to waste.")
        print("")
        print("")
        time.sleep(3.5)
        chapter_nine()
    
    else:
        print("")
        print("")
        print("Incorrect answer, reloading chapter.")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        chapter_eight()


def chapter_seven_b():
    print("")
    print("")
    print("Chapter 7")
    print("")
    time.sleep(3.5)
    print("You run through the dark city, keeping away from any nightwalkers, hearing sounds of screams behind you.")
    print("")
    time.sleep(4)
    print("You make it into a dark alleyway, collapsing on the floor.")
    print("")
    time.sleep(4)
    print("Your mind is spiralling after the scene you’ve just witnessed.")
    print("")
    time.sleep(4)
    print("You’re gripping tight onto the bag of coins, you’ve done it - you have the money.")
    print("")
    time.sleep(4)
    print("You know where the Red Raven’s drop off point is, you make your way there anxiously.")
    print("")
    time.sleep(4)
    print("Just one more corner and then you can save her… if she’s even alive.")
    print("")
    time.sleep(4)
    print("You stop.")
    print("")
    time.sleep(4)
    decision = input("Do you keep the coins and run, expecting it to be a trap or deliver the coins to the Red Raven?[Keep/Deliver]")
    
    if decision == "Keep" or decision == "keep":
        print("")
        print("")
        print("You stand, frozen. How do you know this isn’t a trap? What if she’s not alive and your life is in danger?")
        time.sleep(4)
        print("You look into the reflection of the shop window on your left, you’re just a shell of a man now.")
        time.sleep(4)
        print("You turn around. It’s time for a fresh start.")
        print("")
        print("THE END.")
        print("")
        print("")
        time.sleep(4)
        chapter_endgame()
    
    elif decision == "Deliver" or decision == "deliver":
        print("")
        print("")
        print("You approach the door, and knock the secret way you were told to.")
        print("")
        time.sleep(4)
        print("The door creaks slightly open. ‘Yes?’ a quiet voice asks.")
        print("")
        time.sleep(4)
        print(f"You take a deep breath in and respond ‘It’s {name}, I have the money’.")
        print("")
        time.sleep(4)
        print("The door opens and you’re pulled into the darkness.")
        print("")
        time.sleep(3.5)
        print("‘Please wake up’.")
        print("")
        time.sleep(3.5)
        print("You open your eyes.")
        print("")
        time.sleep(3.5)
        print("It’s her.")
        print("")
        time.sleep(3.5)
        print("Your love.")
        print("")
        time.sleep(3.5)
        print("Your life.")
        print("")
        time.sleep(3.5)
        print("She’s safe")
        print("")
        time.sleep(3.5)
        print(f"‘It’s over, {name}’.")
        print("")
        time.sleep(3.5)
        print("THE END.")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        chapter_endgame()
    
    else:
        print("")
        print("")
        print("Incorrect answer, reloading chapter.")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
    chapter_seven_b()


def chapter_seven():
    print("")
    print("")
    print("Chapter 7")
    print("")
    time.sleep(5)
    print("You wake up and see bars in front of your face, you realise you’re in prison. You slowly let a tear roll down your cheek. It’s over.")
    print("")
    time.sleep(7)
    print("“Oh, awake are you now?” A police officer walks over to your cell. “We caught you at the tailors, stealing his hard earned money - there’s nothing you can do now. But hey, I left the coins out here for you to look at. The police officer’s laugh echoes down the hallway as he leaves the cell area. You can see the large bag of coins you had stuffed in your bag.")
    print("")
    time.sleep(4)
    print(f"'Needing some help here, {name}?' You recognise that voice, James is walking towards your cell. 'No time to explain' James begins to unlock your cell follow me!")
    print("")
    time.sleep(6)
    print("James grabs the bag of coins and leads you through the police station without attracting attention. He walks you back to his home and starts laughing, you’re not sure what’s happening and suddenly feel pain and the world goes black.")
    print("")
    print("")
    time.sleep(3.5)
    chapter_eight()


def chapter_six_b():
    print("")
    print("")
    print("Chapter 6")
    print("")
    print("")
    time.sleep(3.5)
    print(f"The realisation of what you’ve done sets in. You killed a man, yes you {name}.")
    print("")
    time.sleep(4)
    print("You can feel your heartbeat through your entire body, you feel the blood on your body and clothes.")
    print("")
    time.sleep(4)
    decision = input("Do you change out of your blood soaked clothes or escape immediately? [Change/Escape]")
    
    if decision == "Change" or decision == "change":
        print("")
        print("")
        print("You’re terrified of being spotted so you throw off your clothes and begin searching for fresh clothes until you hear police break through the tavern door, there's nowhere to run. GAME OVER.")
        time.sleep(6)
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        start_game()
    
    elif decision == "Escape" or decision == "escape":
        print("")
        print("")
        print("There’s no time to waste, you need to leave now as you hear police nearby, this sparks terror in you and panic sets in. Your urgency intensifies and survival instincts kick in, you see a bag full of gold on a table and you move as quick as lightning back through the window you came through.")
        time.sleep(7)
        print("")
        print("")
        chapter_seven_b()
    
    else: 
        print("")
        print("")
        print("Incorrect answer, reloading chapter.")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        time.sleep(3.5)
        chapter_six_b()


def chapter_six():
    print("")
    print("")
    print("Chapter 6")
    print("")
    time.sleep(3.5)
    print("James: So 50 gold coins, not much - still 1450 to go.")
    print("")
    time.sleep(3.5)
    print("James clicks his fingers “I know, tomorrow is the annual sale from the tailors on the outskirts of town, the amount of money there will be enough for you to pay off your debt, I’ll go in earlier in the day and make sure there will be a way for you to get in.")
    print("")
    time.sleep(7)
    print("You arrive at the tailors at dusk and go to the window where James left it open for you and you climb in. You go to the cupboard underneath the register and start to fill your bag full of gold coins.")
    print("")
    time.sleep(7)
    print("Stealing my coins, are you boy?” a voice sounds from the shadows “the police are on the way, you’re not going anywhere” and suddenly you see the tailor run towards you, throwing his fist in your face.")
    print("")
    time.sleep(3.5)
    print("")
    print("")
    chapter_seven()


def chapter_five_b():
    print("")
    print("")
    time.sleep(3.5)
    print("Chapter 5")
    print("")
    time.sleep(7)
    print("You move slowly, carefully trying to avoid the floorboards creaking.")
    print("")
    time.sleep(3.5)
    print("You take your metal pole from your bag just in case, grab your matches and light one to illuminate the dark corridor.")
    print("")
    time.sleep(4)
    print("You sneak down the hall carefully and come across two rooms, one on the left and one on the right.")
    print("")
    time.sleep(3.5)
    decision = input("Which door do you open? [Left/Right]")
    
    if decision == "Left" or decision == "left":
        print("")
        print("")
        print("You find the stash room with a huge pile of gold. It sure is a sight to behold, the product of a million dreams.You fill your rucksack with as much gold as you can possibly carry, though it doesn’t take long to stir the tavern owner and soon you hear the floor start creaking in the next room.")
        print("")
        print("")
        time.sleep(6)
        chapter_six_b()
    
    elif decision == "Right" or decision == "right":
        print("")
        print("")
        print("You walk right into the tavern owners room. As you open the door, the hinges creak loudly and the owner shoots up out of bed.")
        print("")
        time.sleep(3.5)
        print("'WHO ARE YOU?'")
        print("")
        time.sleep(7)
        print("The fight of your life begins - with one movement, you strike the tavern owner with your metal pipe and he falls to the floor, blood seeping into the floorboards.")
        print("")
        print("")
        time.sleep(3.5)
        chapter_six_b()
    
    else:
        print("")
        print("")
        print("Incorrect answer, reloading chapter.")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        time.sleep(3.5)
        chapter_five_b()


def chapter_five():
    print("")
    print("")
    print("Chapter 5")
    print("")
    time.sleep(3.5)
    print("You gasp loudly and feel immense joy as you feel like your plan is coming together.")
    print("")
    time.sleep(3.5)
    print("Suddenly you hear a growl next to you, turning your head you notice a dog with it’s teeth shining at you.")
    print("")
    time.sleep(3.5)
    decision = input("Try to pet the dog, in an attempt to calm down the animal or run away?[Pet/Run]")
    
    if decision == "Pet" or decision == "pet" or decision == "Animal" or decision == "animal":
        print("")
        print("You hold out your hands for the beast sniff it and it bites your hand, you scream with agony and see blood spurt from your hand - clanking is heard from above as the tavern owners are beginning to run to the source of the noise and you know that you will not be free from this.")
        print("GAME OVER.")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        time.sleep(4)
        start_game()
    
    elif decision == "Run" or decision == "run" or decision == "Away" or decision == "away":
        print("")
        print("")
        print("You jump to your feet and sprint out of the room as quick as lightning, throwing the door closed behind you, you jump out of the window and fall onto the floor, dislocating your arm, you run trying to hold it in place and make it to James’s house.")
        print("")
        print("")
        time.sleep(6)
        chapter_six()
    
    else:
        print("")
        print("")
        print("Incorrect answer, reloading chapter.")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        time.sleep(3.5)
        chapter_five()


def chapter_four():
    print("")
    print("")
    print("Chapter 4")
    print("")
    time.sleep(3.5)
    print("You walk to the tavern in the dark and make it around to the back, where you pull open a window which has luckily been left unlocked.")
    print("")
    time.sleep(5)
    print("You slide yourself through the window into the main tavern area and begin the search.")
    print("")
    time.sleep(3.5)
    decision = input("Do you search the room behind the bar in hopes the money is there or go upstairs? [Room/Upstairs]")
    
    if decision == "Room" or decision == "room":
        print("")
        print("")
        print("You open the door to find the stock of beer and food, ready for the next day, you begin to look through the room and find a cupboard beginning to fall off the hinges, you open it and find a small bag of gold.")
        print("")
        print("")
        time.sleep(3.5)
        chapter_five()
    
    elif decision == "Upstairs" or decision == "upstairs":
        print("")
        print("")
        print("There’s no way that the money would be left unguarded downstairs, you decide to make your way upstairs.")
        print("")
        print("")
        time.sleep(3.5)
        chapter_five_b()
    
    else:
        print("")
        print("")
        print("Incorrect answer, reloading chapter.")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        time.sleep(3)
        chapter_four()


def chapter_three():
    print("")
    print("")
    print("Chapter 3")
    print("")
    time.sleep(2)
    print("As light begins to shine through the window, your friend hands you a cup a tea and begins to recap the trauma.")
    print("")
    time.sleep(3)
    print("James: Okay so lets go through this...  You took a loan with the Red Raven as your stock never arrived for your your shop which you can't afford to pay him back... and he has your wife.")
    print("")
    time.sleep(6)
    print("You: Yes... I have 3 days to pay him or I lose my wife... :'(")
    print("")
    time.sleep(3)
    print("James: We can’t go to the police, of course - borrowing from a loan shark is illegal, you’d be deported back to Romania, wife or not. You need money from somewhere…. I have an idea but you won’t like it.”")
    print("")
    time.sleep(7)
    print("You put your tea down and gulp.")
    print("")
    time.sleep(3)
    print(f"Think of it {name}, you know that I’ve done it many times and gotten out of some sticky situations, you need your wife back and I’d like to spread my wisdom - so, what do you say?”")
    print("")
    time.sleep(6)
    print("You nod to agree and shake hands, all without saying a word. Just an accepting glare into each others eyes.")
    print("")
    time.sleep(3)
    print("You don't know how you ended up in this situation but here you are now, having to steal to make money to save your wife but you don’t have a choice.")
    print("")
    time.sleep(5)
    print("James taught you the basics of stealing and you think you have a chance. You take a rucksack, candle, matches, and a small metal pole, just in case.")
    print("")
    time.sleep(3)
    decision = input("Which of the 2 targets will you strike first? A decrepit run down shack? Or the local tavern? [Tavern/Shack]")
    
    if decision == "Shack" or decision == "shack":
        print("")
        print("")
        print("Since its your first time, you take it nice and slowly, moving 1 plank at a time. You eventually get into the shack and find that its pitch black inside, so you decide to light a match.")
        print("")
        time.sleep(6)
        print("Unfortunately, it turns out this shack is a trap for thieves. The interior floor and walls are covered in pitch, so upon striking the match you fatallly trap yourself in a fire coated prison.")
        print("")
        time.sleep(6)
        print("GAME OVER!")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        start_game()
    
    elif decision == "Tavern" or decision == "tavern":
        print("")
        print("")
        print("You’ve been to the tavern before, before it went all wrong, the amount of gold coins spent there everyday makes you think it’s almost like a bank. A class idea, you think.")
        print("")
        time.sleep(5)
        chapter_four()
    
    else:
        print("")
        print("")
        print("Incorrect answer, reloading chapter.")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        time.sleep(5)
        chapter_three()


def chapter_two():
    print("")
    print("")
    print("Chapter 2")
    print("")
    time.sleep(3)
    print("Under the grip of fear, you drop the note.")
    print("")
    time.sleep(3.5)
    print("You stand there, not knowing what to do. 'How? I- she - what?'")
    print("")
    time.sleep(3.5)
    print("As the adrenaline surges through your body, you race out of the door to the only person that can help you, James.")
    print("")
    time.sleep(4)
    print("You race through the London streets in the dark, trying to find James’s home. You arrive to the front door.")
    print("")
    time.sleep(3.5)
    decision = input("Do you bang on the door furiously and scream his name to wake him up? Or peek through the window? [Door/Peek]")
    if decision == "Door" or decision == "door":
        print("")
        print("")
        print("You cause a commotion in the streets with your loud raps on the door and your frantic yelling.")
        print("")
        time.sleep(3.5)
        print("Lights suddenly appear around the busy streets of London and you feel a hand on your shoulder, pulling you away. 'What do you think you’re doing? Come ‘ere!'")
        print("")
        time.sleep(5)
        print("You land in prison and you never find out what happens to your wife - GAME OVER!")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        time.sleep(3)
        start_game()
    
    elif decision == "Peek" or decision == "peek":
        print("")
        print("")
        print("You go to bang on the door, but remember the police station is around the corner. Cautiously, you peer into the window to see if James is awake.")
        print("")
        time.sleep(5)
        print("You knock on the window and see James sit bolt upright, he turns to see you with your face pressed to the window. You gesture him to let you in and you run to the door, collapsing in tears at his feet.")
        print("")
        print("")
        time.sleep(6)
        chapter_three()
    
    else:
        print("")
        print("")
        print("Incorrect answer, reloading chapter.")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        time.sleep(2.5)
        chapter_two()


def chapter_one():
    print("")
    print("")
    print("Chapter 1")
    print("")
    time.sleep(2.5)
    print("As you toss and turn, you mutter a thought aloud... 'What can I do?'")
    time.sleep(4)
    print("")
    print("'If only that damn ship didn’t get destroyed, I’d be able to survive…. No food, nothing… my poor wife'.")
    time.sleep(4)
    print("")
    print("You turn to face your wife, to put your arm around her and realise she’s not there. You get out of bed and light a candle.")
    time.sleep(4)
    print("")
    print("You realise she’s not in the room at all and notice an envelope under the door of your shack.")
    time.sleep(4)
    print("")
    decision = input("Will you read the note? Or will you discard it? [Read/Discard]")
    
    if decision == "Read" or decision == "read":
        print("")
        print("")
        print("'So you don’t think I need my money? Well, I guess you don’t need your wife. You have 3 days to give me my money, or her life is over - you know where to find me. RR'")
        print("")
        print("")
        chapter_two()
    
    elif decision == "Discard" or decision == "discard":
        print("")
        print("")
        print("You don’t read the letter out of fear.")
        print("")
        time.sleep(3)
        print("You never find out what happened to your wife, and spend your remaining days drinking stolen whiskey.")
        print("")
        time.sleep(4)
        print("GAME OVER!")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        time.sleep(5)
        start_game()
    
    else:
        print("")
        print("")
        print("Incorrect answer, reloading chapter.")
        print("")
        print("")
        print("")
        print("")
        print("")
        print("")
        time.sleep(2.5)
        chapter_one()


def start_game():
        print("Hello and welcome to Ransom.")
        print("")
        time.sleep(2)
        global name
        name = input("What is your name?")
        print("")
        time.sleep(1)
        print(f"Hello {name}! This is a game of choices, even the smallest of choices might land you in the darkest corners of jail, or might have your life cut short.")
        choice = input("Are you sure you want to play the game? [Yes/No]")
        
        if choice == "Yes" or choice == "yes"or choice == "Y" or choice == "y":
            print("")
            print("")
            print("Let the story begin...")
            print("")
            print("")
            print("")
            time.sleep(3.5)
            chapter_one()
        
        elif choice == "No" or choice == "no" or choice == "N" or choice == "n":
            print("")
            print("")
            print("Scared, huh?")
            print("")
            print("")
            print("")
            print("")
            print("")
            print("")
            time.sleep(2.5)
        
        elif choice == "Skip" or choice == "skip":
            chapter_seven()
        
        else:
            print("")
            print("")
            print("Incorrect answer, reloading chapter.")
            print("")
            print("")
            print("")
            print("")
            print("")
            print("")
            time.sleep(2.5)
            start_game()
start_game()